"""Add image column to ChatEntity

Revision ID: 8fd30c5d9dfd
Revises: 945aa9c27140
Create Date: 2025-06-05 18:10:20.280784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd30c5d9dfd'
down_revision: Union[str, None] = '945aa9c27140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('image', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'image')
    # ### end Alembic commands ###
